//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace DAX.CIM.NetSamScada.Asset {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://visue.dk/asset_1_0", IsNullable=false)]
    public partial class Assets {
        
        private Asset[] assetField;
        
        private AssetExt[] assetExtField;
        
        private AssetInfo[] assetInfoField;
        
        private AssetModel[] assetModelField;
        
        private AssetOwner[] assetOwnerField;
        
        private BusbarSectionInfo[] busbarSectionInfoField;
        
        private CableInfo[] cableInfoField;
        
        private CableInfoExt[] cableInfoExtField;
        
        private IdentifiedObject[] identifiedObjectField;
        
        private Maintainer[] maintainerField;
        
        private Manufacturer[] manufacturerField;
        
        private OrganisationRole[] organisationRoleField;
        
        private OverheadWireInfoExt[] overheadWireInfoExtField;
        
        private PetersenCoilInfoExt[] petersenCoilInfoExtField;
        
        private PetersenCoilTapChangerTablePointExt[] petersenCoilTapChangerTablePointExtField;
        
        private ProductAssetModel[] productAssetModelField;
        
        private ShuntCompensatorInfo[] shuntCompensatorInfoField;
        
        private SwitchInfo[] switchInfoField;
        
        private SwitchInfoExt[] switchInfoExtField;
        
        private WireInfo[] wireInfoField;
        
        private WireInfoExt[] wireInfoExtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Asset")]
        public Asset[] Asset {
            get {
                return this.assetField;
            }
            set {
                this.assetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssetExt")]
        public AssetExt[] AssetExt {
            get {
                return this.assetExtField;
            }
            set {
                this.assetExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssetInfo")]
        public AssetInfo[] AssetInfo {
            get {
                return this.assetInfoField;
            }
            set {
                this.assetInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssetModel")]
        public AssetModel[] AssetModel {
            get {
                return this.assetModelField;
            }
            set {
                this.assetModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssetOwner")]
        public AssetOwner[] AssetOwner {
            get {
                return this.assetOwnerField;
            }
            set {
                this.assetOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusbarSectionInfo")]
        public BusbarSectionInfo[] BusbarSectionInfo {
            get {
                return this.busbarSectionInfoField;
            }
            set {
                this.busbarSectionInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CableInfo")]
        public CableInfo[] CableInfo {
            get {
                return this.cableInfoField;
            }
            set {
                this.cableInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CableInfoExt")]
        public CableInfoExt[] CableInfoExt {
            get {
                return this.cableInfoExtField;
            }
            set {
                this.cableInfoExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdentifiedObject")]
        public IdentifiedObject[] IdentifiedObject {
            get {
                return this.identifiedObjectField;
            }
            set {
                this.identifiedObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Maintainer")]
        public Maintainer[] Maintainer {
            get {
                return this.maintainerField;
            }
            set {
                this.maintainerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Manufacturer")]
        public Manufacturer[] Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrganisationRole")]
        public OrganisationRole[] OrganisationRole {
            get {
                return this.organisationRoleField;
            }
            set {
                this.organisationRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OverheadWireInfoExt")]
        public OverheadWireInfoExt[] OverheadWireInfoExt {
            get {
                return this.overheadWireInfoExtField;
            }
            set {
                this.overheadWireInfoExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PetersenCoilInfoExt")]
        public PetersenCoilInfoExt[] PetersenCoilInfoExt {
            get {
                return this.petersenCoilInfoExtField;
            }
            set {
                this.petersenCoilInfoExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PetersenCoilTapChangerTablePointExt")]
        public PetersenCoilTapChangerTablePointExt[] PetersenCoilTapChangerTablePointExt {
            get {
                return this.petersenCoilTapChangerTablePointExtField;
            }
            set {
                this.petersenCoilTapChangerTablePointExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductAssetModel")]
        public ProductAssetModel[] ProductAssetModel {
            get {
                return this.productAssetModelField;
            }
            set {
                this.productAssetModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShuntCompensatorInfo")]
        public ShuntCompensatorInfo[] ShuntCompensatorInfo {
            get {
                return this.shuntCompensatorInfoField;
            }
            set {
                this.shuntCompensatorInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SwitchInfo")]
        public SwitchInfo[] SwitchInfo {
            get {
                return this.switchInfoField;
            }
            set {
                this.switchInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SwitchInfoExt")]
        public SwitchInfoExt[] SwitchInfoExt {
            get {
                return this.switchInfoExtField;
            }
            set {
                this.switchInfoExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WireInfo")]
        public WireInfo[] WireInfo {
            get {
                return this.wireInfoField;
            }
            set {
                this.wireInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WireInfoExt")]
        public WireInfoExt[] WireInfoExt {
            get {
                return this.wireInfoExtField;
            }
            set {
                this.wireInfoExtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Asset : IdentifiedObject {
        
        private string lotNumberField;
        
        private string serialNumberField;
        
        private string typeField;
        
        /// <remarks/>
        public string lotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <remarks/>
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationRole))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Manufacturer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetOrganisationRole))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Maintainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetOwner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductAssetModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WireInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WireInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OverheadWireInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShuntCompensatorInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PetersenCoilInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusbarSectionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Asset))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class IdentifiedObject {
        
        private string mRIDField;
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class PetersenCoilTapChangerTablePointExt {
        
        private CurrentFlow currentField;
        
        private string stepField;
        
        private Voltage voltageField;
        
        /// <remarks/>
        public CurrentFlow current {
            get {
                return this.currentField;
            }
            set {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
            }
        }
        
        /// <remarks/>
        public Voltage voltage {
            get {
                return this.voltageField;
            }
            set {
                this.voltageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class CurrentFlow {
        
        private UnitMultiplier multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private string valueField;
        
        public CurrentFlow() {
            this.unitField = UnitSymbol.A;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum UnitMultiplier {
        
        /// <remarks/>
        c,
        
        /// <remarks/>
        d,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        k,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        micro,
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        p,
        
        /// <remarks/>
        T,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum UnitSymbol {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        deg,
        
        /// <remarks/>
        degC,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        g,
        
        /// <remarks/>
        h,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        Hz,
        
        /// <remarks/>
        J,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        m2,
        
        /// <remarks/>
        m3,
        
        /// <remarks/>
        min,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        ohm,
        
        /// <remarks/>
        Pa,
        
        /// <remarks/>
        rad,
        
        /// <remarks/>
        s,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        VAh,
        
        /// <remarks/>
        VAr,
        
        /// <remarks/>
        VArh,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        Wh,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Voltage {
        
        private UnitMultiplier multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private string valueField;
        
        public Voltage() {
            this.unitField = UnitSymbol.V;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Reactance {
        
        private UnitMultiplier multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private string valueField;
        
        public Reactance() {
            this.unitField = UnitSymbol.ohm;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Resistance {
        
        private UnitMultiplier multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private string valueField;
        
        public Resistance() {
            this.unitField = UnitSymbol.ohm;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Conductance {
        
        private UnitMultiplier multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private string valueField;
        
        public Conductance() {
            this.unitField = UnitSymbol.S;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Susceptance {
        
        private UnitMultiplier multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private string valueField;
        
        public Susceptance() {
            this.unitField = UnitSymbol.S;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class ApparentPower {
        
        private UnitMultiplier multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private string valueField;
        
        public ApparentPower() {
            this.unitField = UnitSymbol.VA;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Manufacturer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetOrganisationRole))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Maintainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetOwner))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class OrganisationRole : IdentifiedObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Manufacturer : OrganisationRole {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Maintainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssetOwner))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public abstract partial class AssetOrganisationRole : OrganisationRole {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class Maintainer : AssetOrganisationRole {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class AssetOwner : AssetOrganisationRole {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductAssetModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class AssetModel : IdentifiedObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class ProductAssetModel : AssetModel {
        
        private ProductAssetModelManufacturer manufacturerField;
        
        /// <remarks/>
        public ProductAssetModelManufacturer Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://visue.dk/asset_1_0")]
    public partial class ProductAssetModelManufacturer {
        
        private string referenceTypeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WireInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WireInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OverheadWireInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShuntCompensatorInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PetersenCoilInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusbarSectionInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class AssetInfo : IdentifiedObject {
        
        private AssetInfoAssetModel assetModelField;
        
        /// <remarks/>
        public AssetInfoAssetModel AssetModel {
            get {
                return this.assetModelField;
            }
            set {
                this.assetModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://visue.dk/asset_1_0")]
    public partial class AssetInfoAssetModel {
        
        private string referenceTypeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WireInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OverheadWireInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfoExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class WireInfo : AssetInfo {
        
        private WireInsulationKind insulationMaterialField;
        
        private bool insulationMaterialFieldSpecified;
        
        private WireMaterialKind materialField;
        
        private bool materialFieldSpecified;
        
        private CurrentFlow ratedCurrentField;
        
        /// <remarks/>
        public WireInsulationKind insulationMaterial {
            get {
                return this.insulationMaterialField;
            }
            set {
                this.insulationMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool insulationMaterialSpecified {
            get {
                return this.insulationMaterialFieldSpecified;
            }
            set {
                this.insulationMaterialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public WireMaterialKind material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialSpecified {
            get {
                return this.materialFieldSpecified;
            }
            set {
                this.materialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow ratedCurrent {
            get {
                return this.ratedCurrentField;
            }
            set {
                this.ratedCurrentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum WireInsulationKind {
        
        /// <remarks/>
        asbestosAndVarnishedCambric,
        
        /// <remarks/>
        beltedPilc,
        
        /// <remarks/>
        butyl,
        
        /// <remarks/>
        crosslinkedPolyethylene,
        
        /// <remarks/>
        ethylenePropyleneRubber,
        
        /// <remarks/>
        highMolecularWeightPolyethylene,
        
        /// <remarks/>
        highPressureFluidFilled,
        
        /// <remarks/>
        lowCapacitanceRubber,
        
        /// <remarks/>
        oilPaper,
        
        /// <remarks/>
        other,
        
        /// <remarks/>
        ozoneResistantRubber,
        
        /// <remarks/>
        rubber,
        
        /// <remarks/>
        siliconRubber,
        
        /// <remarks/>
        treeResistantHighMolecularWeightPolyethylene,
        
        /// <remarks/>
        treeRetardantCrosslinkedPolyethylene,
        
        /// <remarks/>
        unbeltedPilc,
        
        /// <remarks/>
        varnishedCambricCloth,
        
        /// <remarks/>
        varnishedDacronGlass,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum WireMaterialKind {
        
        /// <remarks/>
        acsr,
        
        /// <remarks/>
        aluminum,
        
        /// <remarks/>
        aluminumAlloy,
        
        /// <remarks/>
        aluminumAlloySteel,
        
        /// <remarks/>
        aluminumSteel,
        
        /// <remarks/>
        copper,
        
        /// <remarks/>
        other,
        
        /// <remarks/>
        steel,
        
        /// <remarks/>
        aaac,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OverheadWireInfoExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfoExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class WireInfoExt : WireInfo {
        
        private Susceptance b0chField;
        
        private Susceptance bchField;
        
        private decimal conductorCrossSectionalAreaField;
        
        private bool conductorCrossSectionalAreaFieldSpecified;
        
        private Conductance g0chField;
        
        private Conductance gchField;
        
        private Resistance rField;
        
        private Resistance r0Field;
        
        private Voltage ratedVoltageField;
        
        private CurrentFlow ratedWithstandCurrent1secField;
        
        private Reactance xField;
        
        private Reactance x0Field;
        
        /// <remarks/>
        public Susceptance b0ch {
            get {
                return this.b0chField;
            }
            set {
                this.b0chField = value;
            }
        }
        
        /// <remarks/>
        public Susceptance bch {
            get {
                return this.bchField;
            }
            set {
                this.bchField = value;
            }
        }
        
        /// <remarks/>
        public decimal conductorCrossSectionalArea {
            get {
                return this.conductorCrossSectionalAreaField;
            }
            set {
                this.conductorCrossSectionalAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conductorCrossSectionalAreaSpecified {
            get {
                return this.conductorCrossSectionalAreaFieldSpecified;
            }
            set {
                this.conductorCrossSectionalAreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Conductance g0ch {
            get {
                return this.g0chField;
            }
            set {
                this.g0chField = value;
            }
        }
        
        /// <remarks/>
        public Conductance gch {
            get {
                return this.gchField;
            }
            set {
                this.gchField = value;
            }
        }
        
        /// <remarks/>
        public Resistance r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        public Resistance r0 {
            get {
                return this.r0Field;
            }
            set {
                this.r0Field = value;
            }
        }
        
        /// <remarks/>
        public Voltage ratedVoltage {
            get {
                return this.ratedVoltageField;
            }
            set {
                this.ratedVoltageField = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow ratedWithstandCurrent1sec {
            get {
                return this.ratedWithstandCurrent1secField;
            }
            set {
                this.ratedWithstandCurrent1secField = value;
            }
        }
        
        /// <remarks/>
        public Reactance x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public Reactance x0 {
            get {
                return this.x0Field;
            }
            set {
                this.x0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class OverheadWireInfoExt : WireInfoExt {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CableInfoExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class CableInfo : WireInfoExt {
        
        private CableOuterJacketKind outerJacketKindField;
        
        private bool outerJacketKindFieldSpecified;
        
        private bool sheathAsNeutralField;
        
        private bool sheathAsNeutralFieldSpecified;
        
        private CableShieldMaterialKind shieldMaterialField;
        
        private bool shieldMaterialFieldSpecified;
        
        /// <remarks/>
        public CableOuterJacketKind outerJacketKind {
            get {
                return this.outerJacketKindField;
            }
            set {
                this.outerJacketKindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool outerJacketKindSpecified {
            get {
                return this.outerJacketKindFieldSpecified;
            }
            set {
                this.outerJacketKindFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool sheathAsNeutral {
            get {
                return this.sheathAsNeutralField;
            }
            set {
                this.sheathAsNeutralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sheathAsNeutralSpecified {
            get {
                return this.sheathAsNeutralFieldSpecified;
            }
            set {
                this.sheathAsNeutralFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CableShieldMaterialKind shieldMaterial {
            get {
                return this.shieldMaterialField;
            }
            set {
                this.shieldMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shieldMaterialSpecified {
            get {
                return this.shieldMaterialFieldSpecified;
            }
            set {
                this.shieldMaterialFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum CableOuterJacketKind {
        
        /// <remarks/>
        insulating,
        
        /// <remarks/>
        linearLowDensityPolyethylene,
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        other,
        
        /// <remarks/>
        polyethylene,
        
        /// <remarks/>
        pvc,
        
        /// <remarks/>
        semiconducting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum CableShieldMaterialKind {
        
        /// <remarks/>
        aluminum,
        
        /// <remarks/>
        copper,
        
        /// <remarks/>
        lead,
        
        /// <remarks/>
        other,
        
        /// <remarks/>
        steel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class CableInfoExt : CableInfo {
        
        private string conductorCountField;
        
        private Resistance r0NeutralField;
        
        private Resistance rNeutralField;
        
        private decimal shieldCrossSectionalAreaField;
        
        private bool shieldCrossSectionalAreaFieldSpecified;
        
        private Reactance x0NeutralField;
        
        private Reactance xNeutralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string conductorCount {
            get {
                return this.conductorCountField;
            }
            set {
                this.conductorCountField = value;
            }
        }
        
        /// <remarks/>
        public Resistance r0Neutral {
            get {
                return this.r0NeutralField;
            }
            set {
                this.r0NeutralField = value;
            }
        }
        
        /// <remarks/>
        public Resistance rNeutral {
            get {
                return this.rNeutralField;
            }
            set {
                this.rNeutralField = value;
            }
        }
        
        /// <remarks/>
        public decimal shieldCrossSectionalArea {
            get {
                return this.shieldCrossSectionalAreaField;
            }
            set {
                this.shieldCrossSectionalAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shieldCrossSectionalAreaSpecified {
            get {
                return this.shieldCrossSectionalAreaFieldSpecified;
            }
            set {
                this.shieldCrossSectionalAreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Reactance x0Neutral {
            get {
                return this.x0NeutralField;
            }
            set {
                this.x0NeutralField = value;
            }
        }
        
        /// <remarks/>
        public Reactance xNeutral {
            get {
                return this.xNeutralField;
            }
            set {
                this.xNeutralField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchInfoExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class SwitchInfo : AssetInfo {
        
        private CurrentFlow breakingCapacityField;
        
        private CurrentFlow ratedCurrentField;
        
        private Voltage ratedVoltageField;
        
        /// <remarks/>
        public CurrentFlow breakingCapacity {
            get {
                return this.breakingCapacityField;
            }
            set {
                this.breakingCapacityField = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow ratedCurrent {
            get {
                return this.ratedCurrentField;
            }
            set {
                this.ratedCurrentField = value;
            }
        }
        
        /// <remarks/>
        public Voltage ratedVoltage {
            get {
                return this.ratedVoltageField;
            }
            set {
                this.ratedVoltageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class SwitchInfoExt : SwitchInfo {
        
        private CurrentFlow ratedBreakingCurrentField;
        
        private CurrentFlow ratedMakingCurrentField;
        
        private CurrentFlow ratedWithstandCurrent1secField;
        
        private CurrentFlow ratedWithstandCurrent3sekField;
        
        private string relayFunctionField;
        
        /// <remarks/>
        public CurrentFlow ratedBreakingCurrent {
            get {
                return this.ratedBreakingCurrentField;
            }
            set {
                this.ratedBreakingCurrentField = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow ratedMakingCurrent {
            get {
                return this.ratedMakingCurrentField;
            }
            set {
                this.ratedMakingCurrentField = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow ratedWithstandCurrent1sec {
            get {
                return this.ratedWithstandCurrent1secField;
            }
            set {
                this.ratedWithstandCurrent1secField = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow ratedWithstandCurrent3sek {
            get {
                return this.ratedWithstandCurrent3sekField;
            }
            set {
                this.ratedWithstandCurrent3sekField = value;
            }
        }
        
        /// <remarks/>
        public string relayFunction {
            get {
                return this.relayFunctionField;
            }
            set {
                this.relayFunctionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class ShuntCompensatorInfo : AssetInfo {
        
        private ApparentPower maxPowerLossField;
        
        private CurrentFlow ratedCurrentField;
        
        private Voltage ratedVoltageField;
        
        /// <remarks/>
        public ApparentPower maxPowerLoss {
            get {
                return this.maxPowerLossField;
            }
            set {
                this.maxPowerLossField = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow ratedCurrent {
            get {
                return this.ratedCurrentField;
            }
            set {
                this.ratedCurrentField = value;
            }
        }
        
        /// <remarks/>
        public Voltage ratedVoltage {
            get {
                return this.ratedVoltageField;
            }
            set {
                this.ratedVoltageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class PetersenCoilInfoExt : AssetInfo {
        
        private CoolingKind coolingField;
        
        private bool coolingFieldSpecified;
        
        private CurrentFlow maximumCurrentField;
        
        private CurrentFlow minimumCurrentField;
        
        private PetersenCoilModeKind modeField;
        
        private bool modeFieldSpecified;
        
        private PetersenCoilOperationalLimitKind operationLimitField;
        
        private bool operationLimitFieldSpecified;
        
        private Voltage ratedImpluseWithstandVoltageField;
        
        private Voltage ratedIsolationVoltageField;
        
        private Voltage ratedVoltageField;
        
        /// <remarks/>
        public CoolingKind cooling {
            get {
                return this.coolingField;
            }
            set {
                this.coolingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coolingSpecified {
            get {
                return this.coolingFieldSpecified;
            }
            set {
                this.coolingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow maximumCurrent {
            get {
                return this.maximumCurrentField;
            }
            set {
                this.maximumCurrentField = value;
            }
        }
        
        /// <remarks/>
        public CurrentFlow minimumCurrent {
            get {
                return this.minimumCurrentField;
            }
            set {
                this.minimumCurrentField = value;
            }
        }
        
        /// <remarks/>
        public PetersenCoilModeKind mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PetersenCoilOperationalLimitKind operationLimit {
            get {
                return this.operationLimitField;
            }
            set {
                this.operationLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationLimitSpecified {
            get {
                return this.operationLimitFieldSpecified;
            }
            set {
                this.operationLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Voltage ratedImpluseWithstandVoltage {
            get {
                return this.ratedImpluseWithstandVoltageField;
            }
            set {
                this.ratedImpluseWithstandVoltageField = value;
            }
        }
        
        /// <remarks/>
        public Voltage ratedIsolationVoltage {
            get {
                return this.ratedIsolationVoltageField;
            }
            set {
                this.ratedIsolationVoltageField = value;
            }
        }
        
        /// <remarks/>
        public Voltage ratedVoltage {
            get {
                return this.ratedVoltageField;
            }
            set {
                this.ratedVoltageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum CoolingKind {
        
        /// <remarks/>
        forcedAir,
        
        /// <remarks/>
        forcedOilAndAir,
        
        /// <remarks/>
        other,
        
        /// <remarks/>
        selfCooling,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum PetersenCoilModeKind {
        
        /// <remarks/>
        automaticPositioning,
        
        /// <remarks/>
        @fixed,
        
        /// <remarks/>
        manual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public enum PetersenCoilOperationalLimitKind {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2 hour")]
        Item2hour,
        
        /// <remarks/>
        continuous,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class BusbarSectionInfo : AssetInfo {
        
        private CurrentFlow ratedCurrentField;
        
        private Voltage ratedVoltageField;
        
        /// <remarks/>
        public CurrentFlow ratedCurrent {
            get {
                return this.ratedCurrentField;
            }
            set {
                this.ratedCurrentField = value;
            }
        }
        
        /// <remarks/>
        public Voltage ratedVoltage {
            get {
                return this.ratedVoltageField;
            }
            set {
                this.ratedVoltageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://visue.dk/asset_1_0")]
    public partial class AssetExt : Asset {
        
        private System.DateTime lastMaintenanceDateField;
        
        private bool lastMaintenanceDateFieldSpecified;
        
        /// <remarks/>
        public System.DateTime lastMaintenanceDate {
            get {
                return this.lastMaintenanceDateField;
            }
            set {
                this.lastMaintenanceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastMaintenanceDateSpecified {
            get {
                return this.lastMaintenanceDateFieldSpecified;
            }
            set {
                this.lastMaintenanceDateFieldSpecified = value;
            }
        }
    }
}
